# Generated by Django 3.1.1 on 2020-09-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('division', models.CharField(choices=[('roka', '육군'), ('rokn', '해군'), ('rokaf', '공군'), ('rokm', '해병대'), ('mnd', '국방부직할'), ('civil', '민간인')], default='roka', max_length=5)),
                ('rank', models.CharField(choices=[('pvt', '이병'), ('pfc', '일병'), ('cpl', '상병'), ('sgt', '병장'), ('ssg', '하사'), ('sfc', '중사'), ('msg', '상사'), ('sma', '원사'), ('cwo', '준위'), ('2lt', '소위'), ('lt', '중위'), ('cpt', '대위'), ('maj', '소령'), ('lcl', '중령'), ('col', '대령'), ('bg', '준장'), ('mg', '소장'), ('lg', '중장'), ('gen', '대장'), ('non', '해당사항없음')], default='non', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
