# Generated by Django 3.1.1 on 2020-10-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(default='img', upload_to='profileImgs'),
            preserve_default=False,
        ),
    ]
